options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/togstec-ai/togstec-ai-backend/backend:$COMMIT_SHA',
        '.'
      ]

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/togstec-ai/togstec-ai-backend/backend:$COMMIT_SHA'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'togstec-backend',
        '--image',
        'us-central1-docker.pkg.dev/togstec-ai/togstec-ai-backend/backend:$COMMIT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--port', '8080',
        '--set-secrets',
        'DATABASE_URL=projects/togstec-ai/secrets/NEON_DATABASE_URL:latest'
      ]

